version: "3.9"

networks:
  soulwarm:

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Django/Dockerfile
    networks:
      - soulwarm
    volumes:
      - django_static:/app/backend/static
      - django_media:/app/backend/media
    expose:
      - 8000
    env_file:
      - ./backend/.env # потом вынесем секретные env сюда
    command: gunicorn soulwarm.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    networks:
      - soulwarm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=soulwarm

  react:
    build:
      context: .
      dockerfile: ./docker/React/Dockerfile
    networks:
      - soulwarm
    volumes:
      - react_static:/app/build/static
    expose:
      - 3000
    environment:
      - ENV_API_SERVER=http://localhost
    command: serve -s build -l 3000
    depends_on:
      - backend

  nginx:
    restart: always
    build:
      context: .
      dockerfile: ./docker/Nginx/Dockerfile
    networks:
      - soulwarm
    volumes:
      - django_static:/app/backend/static
      - django_media:/app/backend/media
      - react_static:/app/frontend/build/static
    ports:
      - 80:80
    depends_on:
      - react

volumes:
  postgres_data:
  django_static:
  django_media:
  react_static:
